version: 2.1
parameters:
  RUBY_VERSION:
    type: string
    default: v2

jobs:
  # Selecting right executor
  machine-executor:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: 
          name: "Check OS Version"
          command: lsb_release -d
      - run:
          name: "Check Docker Version"
          command: docker -v
      - run: 
          name: "Check docker-compose Version"
          command: docker-compose -v
      - run:
          name: "Python version"
          command: python --version
      - run: docker ps
      - run:
          name: "Update Python"
          command: | 
            sudo add-apt-repository ppa:deadsnakes/ppa |
            sudo apt-get update -y |
            sudo apt-get install python3.6 -y |
            sudo apt-get install python3.7 -y |
            sudo apt install python3-pip -y |
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 |
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
      - run:
          name: "Python version"
          command: python --version
            
  docker-executor:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
          name: "Check OS Version"
          command: lsb_release -d
      - run:
          name: "Check Docker Version"
          command: docker -v
      - run: 
          name: "Check docker-compose Version"
          command: docker-compose -v
      - run: docker ps
      - run:
          name: "Python version"
          command: python --version
          
  build-macos-medium:
    macos:
      xcode: 13.0.0
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-<<pipeline.parameters.RUBY_VERSION>>-{{ arch }}-{{ .Branch }}-gem-cache-{{ checksum "Gemfile.lock" }}
            - ruby-<<pipeline.parameters.RUBY_VERSION>>-{{ arch }}-{{ .Branch }}-gem-cache-
      - run: bundle install
      - run: bundle clean --force
      - save_cache:
          paths:
            - ~/.bundle
          key: ruby-<<pipeline.parameters.RUBY_VERSION>>-{{ arch }}-{{ .Branch }}-gem-cache-{{ checksum "Gemfile.lock" }}
  
  build-macos-large:
    macos:
      xcode: 13.0.0
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-<<pipeline.parameters.RUBY_VERSION>>-{{ arch }}-{{ .Branch }}-gem-cache-{{ checksum "Gemfile.lock" }}
            - ruby-<<pipeline.parameters.RUBY_VERSION>>-{{ arch }}-{{ .Branch }}-gem-cache-
      - run: bundle install
      - run: bundle clean --force
      - save_cache:
          paths:
            - ~/.bundle
          key: ruby-<<pipeline.parameters.RUBY_VERSION>>-{{ arch }}-{{ .Branch }}-gem-cache-{{ checksum "Gemfile.lock" }}

workflows:
  test-best-practices:
    jobs:
      - machine-executor
      - docker-executor
      - build-macos-medium
      - build-macos-large
      
