version: 2.1

jobs:
  # Selecting right executor
  machine-executor:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: 
          name: "Check OS Version"
          command: lsb_release -d
      - run:
          name: "Check Docker Version"
          command: docker -v
      - run: 
          name: "Check docker-compose Version"
          command: docker-compose -v
      - run:
          name: "Python version"
          command: python --version
            
  docker-executor:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run: 
          name: "Check OS Version"
          command: lsb_release -d
      - run:
          name: "Check Docker Version"
          command: docker -v
      - run: 
          name: "Check docker-compose Version"
          command: docker-compose -v
      - run:
          name: "Python version"
          command: python --version
      

workflows:
  test-best-practices:
    jobs:
      - machine-executor
      - docker-executor
      
