version: 2.1

jobs:
  # Selecting right executor
  build:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: lsb_release -d
      - run: docker -v
      - run: docker-compose -v
