version: 2.1

jobs:
  # Selecting right executor
  build:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: 
          name: "Check OS Version"
          command: lsb_release -d
      - run:
          name: "Check Docker Version"
          command: docker -v
      - run: 
          name: "Check docker-compose Version"
          command: docker-compose -v
      - run:
          name: "Install multiple versions of Python"
          command: |
            sudo apt update && sudo apt upgrade -y |
            sudo apt-get install build-essential checkinstall |
            sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev |
            cd /opt |
            sudo wget https://www.python.org/ftp/python/3.9.2/Python-3.9.2.tgz |
            sudo tar xzf Python-3.9.2.tgz |
            cd Python-3.9.2 |
            sudo ./configure --enable-optimizations |
            sudo make altinstall |
            cd /usr/local/bin/ |
            ls |
            update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 |
            update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.9 2
            

workflows:
  test-best-practices:
    jobs:
      - build
      
